import Head from 'next/head'
import styles from '../styles/Home.module.css'


export async function getServerSideProps (context) {

  context.query // show query parameters aftes ? from url
  context.params // all in params

  //fetch from db
  if(!record) {
    return {
      notFound: true
    }
  }

  const data = await (await fetch('https://google.com').then(t => t.text())).slice(0,200);

  return {
    redirect: {
      destination: 'https://google.com',
      permanent: true // true - status 308, false - 307 and cache disk
    },
    props: {
      data: data
    }
  }
}

// server (SSR) + client (hydration)
export default function Home(props) {
  const {rows} = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Dynamic Site {props.data}
      </main>
    </div>
  )
}
